/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mohamed_muaaz' at '7/20/21 3:39 PM' with Gradle 2.11
 *
 * @author mohamed_muaaz, @date 7/20/21 3:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
